apiVersion: v2
name: webtrees
version: 0.0.0
dependencies:
  - name: app-template
    version: 4.3.0
    repository: https://bjw-s-labs.github.io/helm-charts
  - name: mariadb
    version: 23.2.4
    repository: https://charts.bitnami.com/bitnami