apiVersion: v2
name: webtrees
version: 0.0.0
dependencies:
  - name: app-template
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts
  - name: mariadb
    version: 22.0.0
    repository: https://charts.bitnami.com/bitnami