app-template:
  controllers:
    webtrees:
      pod:
        securityContext:
          fsGroup: 1001
      initContainers:
        install-oauth2-module:
          image:
            repository: alpine
            tag: 3.20
          command:
            - sh
            - -c
            - |
              set -euo pipefail
              apk add --no-cache unzip curl
              mkdir -p /modules_v4
              TMPDIR=$(mktemp -d)
              curl -fsSL -o "$TMPDIR/oauth2_client.zip" https://github.com/Jefferson49/webtrees-oauth2-client/releases/download/v1.1.8/oauth2_client_v1.1.8.zip
              unzip -o "$TMPDIR/oauth2_client.zip" -d "$TMPDIR"
              rm -rf /modules_v4/oauth2_client
              mv "$TMPDIR/oauth2_client" /modules_v4/
      containers:
        app:
          lifecycle:
            postStart:
              exec:
                command:
                  - bin/sh
                  - -c
                  - |
                    echo "lmao yeet"
                    sleep 500
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: 80
                periodSeconds: 10
                failureThreshold: 3
            readiness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: 80
                periodSeconds: 10
            startup:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: 80
                periodSeconds: 10
                failureThreshold: 60
          image:
            repository: dtjs48jkt/webtrees
            tag: 2.2.4
          resources:
            requests:
              cpu: 10m
              memory: 169Mi
            limits:
              memory: 169Mi
          env:
            DB_HOST: webtrees-mariadb
            DB_USER: root
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: webtrees-db
                  key: mariadb-root-password
            DB_NAME: webtrees
            WT_ADMIN: admin
            WT_ADMINPW:
              valueFrom:
                secretKeyRef:
                  name: webtrees
                  key: adminPassword
            WT_ADMINMAIL: admin@localhost
            PRETTY_URLS: "TRUE"
            BASE_URL: "https://family.meyeringh.org"
            DISABLE_SSL: "TRUE"
            PORT: 80
          envFrom:
            - secret: webtrees-sso-secrets
  service:
    app:
      controller: webtrees
      ports:
        http:
          port: 80
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.meyeringh.org"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hosts:
        - host: &host family.meyeringh.org
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: 80
      tls:
        - hosts:
            - *host
          secretName: webtrees-tls-certificate
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      retain: true
      advancedMounts:
        webtrees:
          app:
            - path: /var/www/html/data/
              subPath: data
    modules:
      enabled: true
      type: emptyDir
      advancedMounts:
        webtrees:
          install-oauth2-module:
            - path: /modules_v4
          app:
            - path: /var/www/html/modules_v4
mariadb:
  auth:
    existingSecret: webtrees-db
  primary:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
    resources:
      requests:
        cpu: 22m
        memory: 146Mi
      limits:
        memory: 146Mi
