apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readeck-oauth2-proxy
  namespace: "{{ .Release.Namespace }}"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: readeck-oauth2-proxy
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: dex.readeck
        property: client_secret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: readeck.oauth2-proxy
        property: cookie_secret
