external-secrets:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi

  serviceMonitor:
    enabled: true

  certController:
    resources:
      requests:
        cpu: 10m
        memory: 120Mi
      limits:
        memory: 120Mi
    serviceMonitor:
      enabled: true

  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
    serviceMonitor:
      enabled: true
