external-secrets:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi

  certController:
    resources:
      requests:
        cpu: 10m
        memory: 120Mi
      limits:
        memory: 120Mi

  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 100Mi
