cert-manager:
  installCRDs: true

  resources:
    requests:
      memory: 100Mi
    limits:
      memory: 100Mi

  cainjector:
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 100Mi

  webhook:
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 100Mi

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
