zot:
  resources:
    requests:
      cpu: 10m
      memory: 172Mi
    limits:
      memory: 172Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    className: nginx
    hosts:
      - host: &host registry.meyeringh.org
        paths:
          - path: /
    tls:
      - secretName: zot-tls-certificate
        hosts:
          - *host
  # TODO enable auth
  persistence: true
  pvc:
    create: true
    storage: 10Gi
