loki-stack:
  loki:
    resources:
      requests:
        cpu: 10m
        memory: 400Mi
      limits:
        memory: 400Mi
    serviceMonitor:
      enabled: true

  promtail:
    resources:
      requests:
        cpu: 51m
        memory: 200Mi
      limits:
        memory: 200Mi
