apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-admin
  namespace: "{{ .Release.Namespace }}"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: vaultwarden-admin
  data:
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: vaultwarden.vaultwarden
        property: ADMIN_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-sso-secrets
  namespace: "{{ .Release.Namespace }}"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: vaultwarden-sso-secrets
  data:
    - secretKey: SSO_CLIENT_SECRET
      remoteRef:
        key: dex.vaultwarden
        property: client_secret
