apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.renovate.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    template:
      engineVersion: v2
      data:
        # GitHub token authentication
        RENOVATE_TOKEN: "{{`{{ .token }}`}}"
        GITHUB_COM_TOKEN: "{{`{{ .token }}`}}"
  data:
    - secretKey: token
      remoteRef:
        key: external
        property: renovate-token