apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: "{{ .Release.Namespace }}"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: dex-secrets
  data:
    # Connectors
    - secretKey: KANIDM_CLIENT_ID
      remoteRef:
        key: kanidm.dex
        property: client_id
    - secretKey: KANIDM_CLIENT_SECRET
      remoteRef:
        key: kanidm.dex
        property: client_secret
    # Clients
    - secretKey: GRAFANA_SSO_CLIENT_SECRET
      remoteRef:
        key: dex.grafana
        property: client_secret
    - secretKey: NEXTCLOUD_CLIENT_SECRET
      remoteRef:
        key: dex.nextcloud
        property: client_secret
    - secretKey: PAPERLESS_CLIENT_SECRET
      remoteRef:
        key: dex.paperless
        property: client_secret
    - secretKey: ARGOCD_CLIENT_SECRET
      remoteRef:
        key: dex.argocd
        property: client_secret
    - secretKey: WEBTREES_CLIENT_SECRET
      remoteRef:
        key: dex.webtrees
        property: client_secret
    - secretKey: WEBTREES_TEST_CLIENT_SECRET
      remoteRef:
        key: dex.webtrees-test
        property: client_secret
    - secretKey: JELLYFIN_CLIENT_SECRET
      remoteRef:
        key: dex.jellyfin
        property: client_secret
