external-dns:
  provider: cloudflare
  txtOwnerId: homelab

  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi

  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: value
  extraArgs:
    - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)
  interval: 5m
  triggerLoopOnEvent: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
