cilium_repo_url: https://helm.cilium.io
cilium_version: 1.16.1
cilium_namespace: kube-system
gateway_api_version: v1.2.1
gateway_api_channel: experimental
cilium_values:
  operator:
    replicas: 1
  kubeProxyReplacement: true
  l2announcements:
    enabled: true
  gatewayAPI:
    enabled: true
    enableAppProtocol: true
  # TODO the host and port are k3s-specific, generic solution is in progress
  # https://github.com/cilium/cilium/issues/19038
  # https://github.com/cilium/cilium/pull/28741
  k8sServiceHost: 127.0.0.1
  k8sServicePort: 6444
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
