app-template:
  controllers:
    baikal:
      containers:
        app:
          image:
            repository: ckulka/baikal
            tag: 0.10.1-nginx
  service:
    app:
      controller: baikal
      ports:
        http:
          port: 80
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.meyeringh.org"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"	
      hosts:
        - host: &host dav.meyeringh.org
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: 80
      tls:
        - hosts:
            - *host
          secretName: baikal-tls-certificate
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 10Gi
      advancedMounts:
        baikal:
          app:
            - path: /var/www/baikal/Specific
              subPath: data
            - path: /var/www/baikal/config
              subPath: config
