app-template:
  controllers:
    proton:
      containers:
        app:
          image:
            repository: shenxn/protonmail-bridge
            tag: 3.19.0-1
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
  service:
    app:
      controller: proton
      ports:
        http:
          port: 1025
          targetPort: 25
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host mail.meyeringh.org
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: 1025
      tls:
        - secretName: mail-tls-certificate
          hosts:
            - *host
  persistence:
    state:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      retain: true
      advancedMounts:
        proton-state:
          app:
            - path: /root
              subPath: proton-state
