app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: shenxn/protonmail-bridge
            tag: 3.19.0-1
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          volumeMounts:
            - name: state
              mountPath: /root
              subPath: proton-state
  service:
    main:
      ports:
        http:
          port: 1025
          protocol: HTTP
          targetPort: 25
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host mail.meyeringh.org
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - secretName: mail-tls-certificate
          hosts:
            - *host
  persistence:
    state:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      retain: true
      advancedMounts:
        main:
          main:
            - path: /root
              subPath: proton-state
