- name: Download Gateway API CRDs
  ansible.builtin.get_url:
    url: "https://github.com/kubernetes-sigs/gateway-api/releases/download/{{ gateway_api_version }}/{{ gateway_api_channel }}-install.yaml"
    dest: /tmp/gateway-api-crds.yaml
    mode: "0644"

- name: Install Gateway API CRDs
  kubernetes.core.k8s:
    state: present
    src: /tmp/gateway-api-crds.yaml

- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium
    chart_repo_url: "{{ cilium_repo_url }}"
    chart_version: "{{ cilium_version }}"
    release_namespace: "{{ cilium_namespace }}"
    values: "{{ cilium_values }}"

- name: Wait for Cilium CRDs
  kubernetes.core.k8s_info:
    kind: CustomResourceDefinition
    name: "{{ item }}"
  loop:
    - ciliuml2announcementpolicies.cilium.io
    - ciliumloadbalancerippools.cilium.io
    - gateways.gateway.networking.k8s.io
    - httproutes.gateway.networking.k8s.io
  register: crd
  until: crd.resources | length > 0
  retries: 5
  delay: 10

- name: Apply Cilium resources
  kubernetes.core.k8s:
    template: "{{ item }}"
  loop:
    - ciliuml2announcementpolicy.yaml
    - ciliumloadbalancerippool.yaml
