app-template:
  controllers:
    cloudflared:
      containers:
        app:
          image:
            repository: docker.io/cloudflare/cloudflared
            tag: 2024.4.0
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
  configMaps:
    config:
      enabled: true
      data:
        config.yaml: |
          tunnel: homelab
          credentials-file: /etc/cloudflared/credentials.json
          metrics: 0.0.0.0:2000
          no-autoupdate: true
          ingress:
            - hostname: minecraft.meyeringh.org
              service: tcp://ingress-nginx-controller.ingress-nginx:25565
            - hostname: '*.meyeringh.org'
              service: https://ingress-nginx-controller.ingress-nginx
              originRequest:
                noTLSVerify: true
            - service: http_status:404
  persistence:
    config:
      enabled: true
      type: configMap
      name: cloudflared-config
      globalMounts:
        - path: /etc/cloudflared/config.yaml
          subPath: config.yaml
    credentials:
      enabled: true
      type: secret
      # Created by ../../external/cloudflared
      name: cloudflared-credentials
      globalMounts:
        - path: /etc/cloudflared/credentials.json
          subPath: credentials.json
