app-template:
  serviceAccount:
    tailscale: {}
  controllers:
    tailscale:
      serviceAccount:
        identifier: tailscale
      containers:
        app:
          image:
            repository: ghcr.io/tailscale/tailscale
            tag: v1.88.4
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
          env:
            TS_HOSTNAME: homelab-router
            TS_USERSPACE: false
            TS_KUBE_SECRET: tailscale
            TS_ROUTES: 192.168.1.0/24
            TS_AUTHKEY:
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
