apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: "{{ .Release.Name }}-postgres"
  namespace: "{{ .Release.Namespace }}"
spec:
  instances: 1
  imageName: {{ .Values.postgresImage }}
  bootstrap:
    initdb:
      database: webtrees
      owner: webtrees
  storage:
    size: 5Gi
  monitoring:
    enablePodMonitor: true
