apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  dataFrom:
    - extract:
        key: webtrees.webtrees

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webtrees-sso-secrets
  namespace: "{{ .Release.Namespace }}"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: webtrees-sso-secrets
  data:
    - secretKey: WEBTREES_CLIENT_SECRET
      remoteRef:
        key: dex.webtrees
        property: client_secret
