gitea:
  resources:
    requests:
      cpu: 10m
      memory: 163Mi
    limits:
      memory: 163Mi

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: &host git.meyeringh.org
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    oauth:
    - name: Dex
      provider: openidConnect
      existingSecret: gitea-sso-secrets
      autoDiscoverUrl: https://dex.meyeringh.org/.well-known/openid-configuration
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.meyeringh.org
        OFFLINE_MODE: true
      repository:
        DISABLED_REPO_UNITS: repo.wiki,repo.projects,repo.packages
        DISABLE_STARS: true
        DEFAULT_BRANCH: master
      oauth2_client:
        ENABLE_AUTO_REGISTRATION: true
        # We dont't set USERNAME and stuff here, because no matter what i tried i could not get it to work. So now the user has to set his username and email afer initial login.
      service.explore:
        DISABLE_USERS_PAGE: true
      actions:
        ENABLED: false
      webhook:
        ALLOWED_HOST_LIST: private
    additionalConfigFromEnvs:
      - name: GITEA__mailer__ENABLED
        value: "true"
      - name: GITEA__mailer__PROTOCOL
        value: "smtp+starttls"
      - name: GITEA__mailer__SMTP_ADDR
        value: mail.meyeringh.org
      - name: GITEA__mailer__SMTP_PORT
        value: "587"
      - name: GITEA__mailer__USER
        valueFrom:
          secretKeyRef:
            name: gitea-mail-secret
            key: username
      - name: GITEA__mailer__PASSWD
        valueFrom:
          secretKeyRef:
            name: gitea-mail-secret
            key: password
      - name: GITEA__mailer__FROM
        valueFrom:
          secretKeyRef:
            name: gitea-mail-secret
            key: sender_mail