renovate:
  cronjob:
    schedule: '0 * * * *'  # Hourly: each run stops after two automerges
  renovate:
    config: |
      {
        "platform": "github",
        "repositories": ["meyeringh/homelab"],
        "automerge": true,
        "automergeType": "branch",
        "ignoreTests": true,
        "hostRules": [
          {
            "matchHost": "lscr.io",
            "concurrentRequestLimit": 2,
            "maxRequestsPerSecond": 1
          }
        ],
        "packageRules": [
          {
            "matchUpdateTypes": ["major"],
            "automerge": false,
            "prPriority": 10
          }
        ]
      }
  existingSecret: renovate-secret
