grafana:
  resources:
    requests:
      cpu: 78m
      memory: 264Mi
    limits:
      memory: 264Mi

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - &host grafana.meyeringh.org
    tls:
      - secretName: grafana-general-tls
        hosts:
          - *host
  envFromSecret: grafana-secrets
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-system-kube-pro-prometheus.monitoring-system:9090
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://loki.loki:3100
          access: proxy
  grafana.ini:
    server:
      root_url: https://grafana.meyeringh.org
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      name: Dex
      client_id: grafana-sso
      client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
      scopes: openid profile email groups
      auth_url: https://dex.meyeringh.org/auth
      token_url: https://dex.meyeringh.org/token
      api_url: https://dex.meyeringh.org/userinfo
