app-template:
  controllers:
    kanidm:
      type: statefulset
      containers:
        app:
          image:
            repository: docker.io/kanidm/server
            tag: 1.10.1
        # TODO remove when Cilium supports BackendTLSPolicy (upstream TLS)
        tls-proxy:
          image:
            repository: docker.io/nginx
            tag: alpine
      statefulset:
        volumeClaimTemplates:
          - name: data
            size: 1Gi
            globalMounts:
              - path: /data
            accessMode: "ReadWriteOnce"
  configMaps:
    config:
      enabled: true
      data:
        server.toml: |
          bindaddress = "[::]:443"
          ldapbindaddress = "[::]:636"
          trust_x_forward_for = true
          db_path = "/data/kanidm.db"
          tls_chain = "/data/ca.crt"
          tls_key = "/data/tls.key"
          domain = "auth.meyeringh.org"
          origin = "https://auth.meyeringh.org"
    nginx:
      enabled: true
      data:
        default.conf: |
          server {
              listen 8080;
              location / {
                  proxy_pass https://127.0.0.1:443;
                  proxy_ssl_verify off;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
  service:
    app:
      controller: kanidm
      ports:
        http:
          port: 8080
          targetPort: 8080
        https:
          port: 443
        ldap:
          port: 636
  ingress:
    main:
      enabled: false

  route:
    main:
      parentRefs:
        - name: main
          namespace: gateway
          sectionName: https
      hostnames:
        - auth.meyeringh.org
      annotations:
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.meyeringh.org"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      rules:
        - backendRefs:
            - identifier: app
              port: 8080
  persistence:
    config:
      enabled: true
      type: configMap
      identifier: config
      advancedMounts:
        kanidm:
          app:
            - path: /data/server.toml
              subPath: server.toml
    nginx-config:
      enabled: true
      type: configMap
      identifier: nginx
      advancedMounts:
        kanidm:
          tls-proxy:
            - path: /etc/nginx/conf.d/default.conf
              subPath: default.conf
    tls:
      enabled: true
      type: secret
      name: kanidm-selfsigned-certificate
      advancedMounts:
        kanidm:
          app:
            - path: /data/ca.crt
              subPath: ca.crt
            - path: /data/tls.key
              subPath: tls.key
