app-template:
  controllers:
    kanidm:
      type: statefulset
      containers:
        app:
          image:
            repository: docker.io/kanidm/server
            tag: 1.4.6
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
>>>>>>> parent of 51ec4b3 (Revert "Reapply "kanidm: update 1.4"")
      statefulset:
        volumeClaimTemplates:
          - name: data
            size: 1Gi
            globalMounts:
              - path: /data
            accessMode: "ReadWriteOnce"
  configMaps:
    config:
      enabled: true
      data:
        server.toml: |
          bindaddress = "[::]:443"
          ldapbindaddress = "[::]:636"
          trust_x_forward_for = true
          db_path = "/data/kanidm.db"
          tls_chain = "/data/ca.crt"
          tls_key = "/data/tls.key"
          domain = "auth.meyeringh.org"
          origin = "https://auth.meyeringh.org"
  service:
    app:
      controller: kanidm
      ports:
        http:
          port: 80
        https:
          port: 443
        ldap:
          port: 636
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      hosts:
        - host: &host auth.meyeringh.org
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: 443
      tls:
        - hosts:
            - *host
          secretName: kanidm-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      identifier: config
      globalMounts:
        - path: /data/server.toml
          subPath: server.toml
    tls:
      enabled: true
      type: secret
      name: kanidm-selfsigned-certificate
      globalMounts:
        - path: /data/ca.crt
          subPath: ca.crt
        - path: /data/tls.key
          subPath: tls.key
