app-template:
  controllers:
    kanidm:
      type: statefulset
      containers:
        app:
          image:
            repository: docker.io/kanidm/server
            tag: 1.9.2
      statefulset:
        volumeClaimTemplates:
          - name: data
            size: 1Gi
            globalMounts:
              - path: /data
            accessMode: "ReadWriteOnce"
  configMaps:
    config:
      enabled: true
      data:
        server.toml: |
          bindaddress = "[::]:443"
          ldapbindaddress = "[::]:636"
          trust_x_forward_for = true
          db_path = "/data/kanidm.db"
          tls_chain = "/data/ca.crt"
          tls_key = "/data/tls.key"
          domain = "auth.meyeringh.org"
          origin = "https://auth.meyeringh.org"
  service:
    app:
      controller: kanidm
      ports:
        http:
          port: 80
        https:
          port: 443
          appProtocol: https
        ldap:
          port: 636
  ingress:
    main:
      enabled: false

  route:
    main:
      parentRefs:
        - name: main
          namespace: gateway
          sectionName: https
      hostnames:
        - auth.meyeringh.org
      annotations:
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.meyeringh.org"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      rules:
        - backendRefs:
            - identifier: app
              port: 443
  persistence:
    config:
      enabled: true
      type: configMap
      identifier: config
      globalMounts:
        - path: /data/server.toml
          subPath: server.toml
    tls:
      enabled: true
      type: secret
      name: kanidm-selfsigned-certificate
      globalMounts:
        - path: /data/ca.crt
          subPath: ca.crt
        - path: /data/tls.key
          subPath: tls.key
