apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-secret
  namespace: "{{ .Release.Namespace }}"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: linkwarden-secret
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: linkwarden.linkwarden
        property: nextauth_secret
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: linkwarden.linkwarden
        property: meili_master_key
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: dex.linkwarden
        property: client_secret
