apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: "{{ .Release.Name }}-postgres"
  namespace: "{{ .Release.Namespace }}"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  bootstrap:
    initdb:
      database: joplin
      owner: joplin
  storage:
    size: 8Gi
  monitoring:
    enablePodMonitor: true