apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: "{{ .Release.Name }}-postgres"
  namespace: "{{ .Release.Namespace }}"
spec:
  imageCatalogRef:
    major: 17
  instances: 1
  bootstrap:
    initdb:
      database: joplin
      owner: joplin
  storage:
    size: 8Gi
  monitoring:
    enablePodMonitor: true