home-assistant:
  env:
    - name: TZ
      value: Europe/Berlin

  resources:
    requests:
      cpu: 10m
      memory: 500Mi
    limits:
      memory: 500Mi

  service:
    type: ClusterIP
    port: 8123

  ingress:
    enabled: false

  configuration:
    enabled: true
    forceInit: true
    trusted_proxies:
      - 10.0.0.0/8

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
