home-assistant:
  env:
    - name: TZ
      value: Europe/Berlin

  resources:
    requests:
      cpu: 10m
      memory: 360Mi
    limits:
      memory: 360Mi

  service:
    type: ClusterIP
    port: 8123

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.meyeringh.org"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &host home.meyeringh.org
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: 8123
    tls:
      - hosts:
          - *host
        secretName: home-tls-certificate

  configuration:
    enabled: true
    forceInit: true
    trusted_proxies:
      - 10.0.0.0/8

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
