apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
spec:
  description: System layer core components (ingress, cert-manager, etc.)
  sourceRepos:
    - '*'
  destinations:
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: loki
      server: https://kubernetes.default.svc
    - namespace: monitoring-system
      server: https://kubernetes.default.svc
    - namespace: rook-ceph
      server: https://kubernetes.default.svc
    - namespace: volsync-system
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist: []
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Shared platform services (identity, git, observability, secrets)
  sourceRepos:
    - '*'
  destinations:
    - namespace: grafana
      server: https://kubernetes.default.svc
    - namespace: gitea
      server: https://kubernetes.default.svc
    - namespace: dex
      server: https://kubernetes.default.svc
    - namespace: kanidm
      server: https://kubernetes.default.svc
    - namespace: global-secrets
      server: https://kubernetes.default.svc
    - namespace: proton
      server: https://kubernetes.default.svc
    - namespace: zot
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: End-user applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  orphanedResources:
    warn: true
