apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret-oidc
  namespace: "{{ .Release.Namespace }}"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: oidc.dex.clientSecret
      remoteRef:
        key: dex.argocd
        property: client_secret
