apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-sso-secrets
  namespace: "{{ .Release.Namespace }}"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: gitea-sso-secrets
  data:
    - secretKey: secret
      remoteRef:
        key: dex.gitea
        property: client_secret
