apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wireguard-config
  namespace: "{{ .Release.Namespace }}"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: wireguard-config
    template:
      engineVersion: v2
      data:
        wg0.conf: |
          [Interface]
          Address = 10.13.13.1/24
          ListenPort = 51820
          PrivateKey = {{ `{{ .privateKey }}` }}
          PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
          PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
          {{- range .Values.peers }}

          [Peer]
          # {{ .name }}
          PublicKey = {{ .publicKey }}
          AllowedIPs = {{ .allowedIPs }}
          {{- end }}
  data:
    - secretKey: privateKey
      remoteRef:
        key: external
        property: wireguard-private-key
