#!/bin/sh

set -eu

export KUBECONFIG=./metal/kubeconfig.yaml

kubectl get gateways --all-namespaces --no-headers --output custom-columns="GATEWAY:.metadata.name,ADDRESS:.status.addresses[0].value"
kubectl get httproutes --all-namespaces --no-headers --output custom-columns="NAMESPACE:.metadata.namespace,HOST:.spec.hostnames[0]"
