apiVersion: v1
kind: Service
metadata:
  name: proton-smtp
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: proton
  ports:
    - name: smtp
      port: 587
      targetPort: 1025
      protocol: TCP
