apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: proton
spec:
  provider:
    kubernetes:
      remoteNamespace: proton
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: proton
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets-kubernetes-proton
          namespace: proton
