cf-switch:
  env:
    DEST_HOSTNAMES:
      value: "paperless.meyeringh.org,media.meyeringh.org,auth.meyeringh.org,dex.meyeringh.org"
    CLOUDFLARE_ZONE_ID:
      value: "fba9ac534a86b7363e4864046275a256"
    CLOUDFLARE_API_TOKEN:
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: token
  ingress:
    enabled: false