- hosts: localhost
  tasks:
    - name: Ensure required namespaces exist
      kubernetes.core.k8s:
        kubeconfig: ../metal/kubeconfig.yaml
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
        state: present
      loop:
        - cert-manager
        - external-dns
        - global-secrets
        - monitoring-system
        - cloudflare-ddns
