app-template:
  controllers:
    minecraft:
      pod:
        securityContext:
          fsGroup: 1000
      initContainers:
        fix-permissions:
          image:
            repository: busybox
            tag: latest
          command:
            - sh
            - -c
            - |
              # Create directories if they don't exist
              mkdir -p /data/config-lgsm/pmcserver
              mkdir -p /data/serverfiles
              mkdir -p /data/serverfiles/plugins
              # Copy config files with correct permissions
              cp /tmp/config/common.cfg /data/config-lgsm/pmcserver/common.cfg
              cp /tmp/config/server.properties /data/serverfiles/server.properties
              cp /tmp/config/eula.txt /data/serverfiles/eula.txt
              # Get plugins
              wget https://github.com/dmulloy2/ProtocolLib/releases/download/5.3.0/ProtocolLib.jar -O /data/serverfiles/plugins/ProtocolLib.jar
              wget https://www.spigotmc.org/resources/loginsecurity.19362/download?version=524224 -O /data/serverfiles/plugins/LoginSecurity.jar
              # Set ownership to linuxgsm user (UID 1000)
              chown -R 1000:1000 /data
              chmod 644 /data/config-lgsm/pmcserver/common.cfg /data/serverfiles/server.properties /data/serverfiles/eula.txt
              chmod 744 /data/serverfiles/plugins/ProtocolLib.jar /data/serverfiles/plugins/LoginSecurity.jar
      containers:
        app:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          image:
            repository: gameservermanagers/gameserver
            tag: pmc
          resources:
            requests:
              cpu: 10m
              memory: 1500Mi
            limits:
              memory: 1500Mi
  configMaps:
    config:
      enabled: true
      data:
        common.cfg: |
          ##################################
          ######## Common Settings #########
          ##################################
          # PLACE GLOBAL SETTINGS HERE
          ## These settings will apply to all instances.

          #### Game Server Settings ####
          javaram="1024"
          mcversion="1.20.6"
          branch="release"
        server.properties: |
          # Minecraft Server Properties
          gamemode=survival
          motd=\u00a77\u00a7ku\u00a7f\u00a7ku\u00a77\u00a7ku\u00a7f \u25b6\u00a7r \u00a7nWelcome \u00a78\u00a7nto\u00a7r\u00a7n the \u00a78\u00a7nserver\u00a7f \u25c0\u00a77\u00a7k u\u00a7f\u00a7ku\u00a77\u00a7ku
          white-list=true
          spawn-protection=0
          difficulty=2
          online-mode=false
        eula.txt: |
          # Minecraft End User License Agreement
          # This must be true to run the server.
          eula=true
  service:
    app:
      controller: minecraft
      ports:
        minecraft:
          port: 25565
          targetPort: 25565
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host minecraft.meyeringh.org
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: app
                port: 25565
      tls:
        - secretName: minecraft-tls-certificate
          hosts:
            - *host
  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      retain: true
      advancedMounts:
        minecraft:
          app:
            - path: /data
              subPath: data
          fix-permissions:
            - path: /data
              subPath: data
    config-temp:
      enabled: true
      type: configMap
      identifier: config
      advancedMounts:
        minecraft:
          fix-permissions:
            - path: /tmp/config
