apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-files-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-files-pvc
spec:
  storageClassName: ""
  volumeName: my-files-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
